-- KPB launch countries seed (from product annex 04)
-- Usage:
--   psql "$DATABASE_URL" -f backend/scripts/seed-kpb-countries.sql

INSERT INTO "Country" (
  "id",
  "nameFr",
  "nameEn",
  "whyStudyFr",
  "whyStudyEn",
  "tuitionRangeFr",
  "tuitionRangeEn",
  "livingCostRangeFr",
  "livingCostRangeEn",
  "visaOverviewFr",
  "visaOverviewEn",
  "admissionDifficultyFr",
  "admissionDifficultyEn",
  "popularFieldIds",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'fra',
    'France',
    'France',
    'Destination phare avec ecoles privees partenaires KPB.',
    'Top destination with private schools KPB partnerships.',
    '5000-18000 EUR/an',
    '5000-18000 EUR/year',
    '800-1200 EUR/mois',
    '800-1200 EUR/month',
    'Visa etudiant long sejour.',
    'Long-stay student visa.',
    'Moyenne',
    'Medium',
    ARRAY[]::text[],
    now(),
    now()
  ),
  (
    'deu',
    'Allemagne',
    'Germany',
    'Universites publiques a frais faibles + parcours langue.',
    'Low-fee public universities + language path.',
    '0-1500 EUR/an',
    '0-1500 EUR/year',
    '900-1100 EUR/mois',
    '900-1100 EUR/month',
    'Compte bloque requis.',
    'Blocked account required.',
    'Moyenne',
    'Medium',
    ARRAY[]::text[],
    now(),
    now()
  ),
  (
    'usa',
    'USA',
    'USA',
    'Large ecosysteme universitaire anglophone.',
    'Large English-speaking university ecosystem.',
    '15000-50000 EUR/an',
    '15000-50000 EUR/year',
    '1000-1400 EUR/mois',
    '1000-1400 EUR/month',
    'Visa F-1.',
    'F-1 visa.',
    'Haute',
    'High',
    ARRAY[]::text[],
    now(),
    now()
  ),
  (
    'can',
    'Canada',
    'Canada',
    'Qualite de vie et voies post-etudes.',
    'Quality of life and post-study pathways.',
    '7000-25000 EUR/an',
    '7000-25000 EUR/year',
    '900-1300 EUR/mois',
    '900-1300 EUR/month',
    'Permis etudiant + options post-diplome.',
    'Student permit + post-graduation options.',
    'Moyenne',
    'Medium',
    ARRAY[]::text[],
    now(),
    now()
  ),
  (
    'mar',
    'Maroc',
    'Morocco',
    'Option francophone accessible pour Afrique de l Ouest.',
    'Accessible French-speaking destination for West Africa.',
    '2500-6000 EUR/an',
    '2500-6000 EUR/year',
    '300-550 EUR/mois',
    '300-550 EUR/month',
    'Visa etudiant selon nationalite.',
    'Student visa by nationality.',
    'Faible',
    'Low',
    ARRAY[]::text[],
    now(),
    now()
  ),
  (
    'tur',
    'Turquie',
    'Turkey',
    'Campus modernes et cout maitrise.',
    'Modern campuses and controlled costs.',
    '4000-12000 EUR/an',
    '4000-12000 EUR/year',
    '400-700 EUR/mois',
    '400-700 EUR/month',
    'Visa etudiant standard.',
    'Standard student visa.',
    'Moyenne',
    'Medium',
    ARRAY[]::text[],
    now(),
    now()
  ),
  (
    'are',
    'EAU (Dubai)',
    'UAE (Dubai)',
    'Programmes anglophones professionnalisants.',
    'Career-oriented English programs.',
    '6000-12000 EUR/an',
    '6000-12000 EUR/year',
    '900-1400 EUR/mois',
    '900-1400 EUR/month',
    'Visa etudiant sponsorise par l etablissement.',
    'Institution-sponsored student visa.',
    'Moyenne',
    'Medium',
    ARRAY[]::text[],
    now(),
    now()
  ),
  (
    'gbr',
    'Royaume-Uni',
    'United Kingdom',
    'Universites prestigieuses en anglais natif.',
    'Prestigious universities with native English.',
    '13000-35000 EUR/an',
    '13000-35000 EUR/year',
    '1000-1600 EUR/mois',
    '1000-1600 EUR/month',
    'Student visa UK.',
    'UK student visa.',
    'Haute',
    'High',
    ARRAY[]::text[],
    now(),
    now()
  ),
  (
    'esp',
    'Espagne',
    'Spain',
    'Programmes internationaux a Madrid.',
    'International programs in Madrid.',
    '15000-20000 EUR/an',
    '15000-20000 EUR/year',
    '700-1100 EUR/mois',
    '700-1100 EUR/month',
    'Visa etudiant Schengen.',
    'Schengen student visa.',
    'Moyenne',
    'Medium',
    ARRAY[]::text[],
    now(),
    now()
  )
ON CONFLICT ("id") DO UPDATE SET
  "nameFr" = EXCLUDED."nameFr",
  "nameEn" = EXCLUDED."nameEn",
  "whyStudyFr" = EXCLUDED."whyStudyFr",
  "whyStudyEn" = EXCLUDED."whyStudyEn",
  "tuitionRangeFr" = EXCLUDED."tuitionRangeFr",
  "tuitionRangeEn" = EXCLUDED."tuitionRangeEn",
  "livingCostRangeFr" = EXCLUDED."livingCostRangeFr",
  "livingCostRangeEn" = EXCLUDED."livingCostRangeEn",
  "visaOverviewFr" = EXCLUDED."visaOverviewFr",
  "visaOverviewEn" = EXCLUDED."visaOverviewEn",
  "admissionDifficultyFr" = EXCLUDED."admissionDifficultyFr",
  "admissionDifficultyEn" = EXCLUDED."admissionDifficultyEn",
  "updatedAt" = now();
