// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7D1hwMfG18r3paVjugyyCECCz_X4avxs',
    appId: '1:334788383631:android:4d5ce891b039cf1b7d71fa',
    messagingSenderId: '334788383631',
    projectId: 'karatoupostbac-178213',
    databaseURL: 'https://karatoupostbac-178213.firebaseio.com',
    storageBucket: 'karatoupostbac-178213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnorVz_483TpEnVHvcJrAyzVtjQgjH6-8',
    appId: '1:334788383631:ios:0acae0ce5b848e0a',
    messagingSenderId: '334788383631',
    projectId: 'karatoupostbac-178213',
    databaseURL: 'https://karatoupostbac-178213.firebaseio.com',
    storageBucket: 'karatoupostbac-178213.firebasestorage.app',
    iosClientId:
        '334788383631-59cfd9gdtauqpmnfvo1uju8qhmtkrk8b.apps.googleusercontent.com',
    // Bundle id of the EXISTING App Store app (id 1128659292) — a published
    // app's bundle id can never change, so the binary must keep it.
    iosBundleId: 'Karatou.karatou',
  );
}
